### ISSUE TITLE
program hangs

### ISSUE THREAD

**Issue by Prutsen** [Galch/DustViewerSharp#7]
I have run the program on several Windows 7 computers with two different SDS011 sensors, and the program hangs after a couple of minutes... restarting the program resumes measuring until the next stall... any suggestions on what is going wrong? Otherwise a very useful program!

**Comment by michelprog** [comment]
I have the same issue and looked at the code. It is a bug in the program; once it receives unexpected or corrupted input on the serial bus, it can not recover from it.

A simple solution to it is to add the following line to the serialPort1_DataReceived() function and it is solved.

if (data_acc.Count() > 40) data_acc.Clear();

**Comment by galch** [comment]
@Prutsen , @michelprog First of all, thank you for your interest in my project.

I have revised and uploaded the code to address this issue on the branch below, so please check and let me know if it works well.

https://github.com/Galch/DustViewerSharp/tree/iss7_fixHangs

**Comment by michelprog** [comment]
That solves the problem. I have run it for about an hour without hangs now. Thank you.

**Comment by Prutsen** [comment]
Hi, All,


thank you very much for fixing the program, I ran it yesterday for over 
2 hours with large concentration measurement swings with no problems at 
all. I use the programme for fit testing medical face masks and find it 
very useful.


Thanks again,


Nino. (Prutsen)
